version: '3.8'

services:
  chromadb-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: chromadb-app
    ports:
      - "5100:5100"
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./logs:/app/logs
    env_file:
      - .env
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5100/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    user: root
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    networks:
      - app-network

networks:
  app-network:
    driver: bridge